<?php
if ( ! defined( 'ABSPATH' ) ) exit;

class Fotonic_Admin_Page {
    public static function add_menu(): void {
        $icon_svg = file_get_contents( FOTONIC_DIR . '.wordpress-org/fotonic-icon-only.svg' );
        $icon_url = 'data:image/svg+xml;base64,' . base64_encode( $icon_svg );
        add_menu_page(
            esc_html__( 'Fotonic', 'fotonic' ),
            esc_html__( 'Fotonic', 'fotonic' ),
            'manage_options',
            'fotonic',
            [ __CLASS__, 'render' ],
            $icon_url,
            25
        );
    }

    public static function render(): void {
        echo '<div class="wrap"><div id="fotonic-app-root"></div></div>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Static HTML, no user data.
    }

    /**
     * Add type="module" to the Vite ES-module bundle.
     * Vite's default app build emits top-level import statements, which browsers
     * only accept inside <script type="module"> tags.
     */
    public static function add_module_type( string $tag, string $handle ): string {
        if ( 'fotonic-app-js' !== $handle && 'fotonic-pro-js' !== $handle ) {
            return $tag;
        }
        return str_replace( '<script ', '<script type="module" ', $tag );
    }

    /**
     * Remove all admin notices on the Fotonic SPA page to prevent double scrollbars.
     * Hooked to `all_admin_notices` at priority PHP_INT_MAX so it fires after everything else.
     */
    public static function suppress_notices(): void {
        $page = isset( $_GET['page'] ) ? sanitize_key( $_GET['page'] ) : ''; // phpcs:ignore WordPress.Security.NonceVerification.Recommended
        if ( 'fotonic' !== $page ) {
            return;
        }
        remove_all_actions( 'admin_notices' );
        remove_all_actions( 'all_admin_notices' );
        remove_all_actions( 'network_admin_notices' );
        remove_all_actions( 'user_admin_notices' );
    }

    public static function enqueue_assets( string $hook ): void {
        if ( 'toplevel_page_fotonic' !== $hook ) {
            return;
        }

        // Inline CSS: hide any residual notices and kill the page-level scrollbar on the SPA page.
        wp_add_inline_style( 'fotonic-app-css', '
            .notice, .notice-error, .notice-warning, .notice-info, .notice-success,
            .update-nag, .updated, .error, .wp-browser-update,
            #wpbody-content > .updated, #wpbody-content > .error { display: none !important; }
            body.toplevel_page_fotonic, body.toplevel_page_fotonic #wpbody-content,
            body.toplevel_page_fotonic #wpwrap { overflow: hidden !important; }
            body.toplevel_page_fotonic #wpwrap #wpfooter { display: none !important; }
            #wpbody-content { padding-bottom: 0 !important; }
        ' );

        add_filter( 'script_loader_tag', [ __CLASS__, 'add_module_type' ], 10, 2 );

        wp_enqueue_editor();
        wp_enqueue_media();

        wp_enqueue_script(
            'fotonic-app-js',
            FOTONIC_URL . 'dist/fotonic-app.js',
            [ 'wp-i18n' ], // wp-i18n provides window.wp.i18n used by @wordpress/i18n
            FOTONIC_VERSION,
            [ 'in_footer' => true ]
        );

        wp_enqueue_style(
            'fotonic-app-css',
            FOTONIC_URL . 'dist/fotonic-app.css',
            [],
            FOTONIC_VERSION
        );

        // Read WP admin theme colors from DOM before React renders.
        // getComputedStyle works for all built-in and custom color schemes.
        wp_add_inline_script( 'fotonic-app-js', '(function(){
  var root = document.getElementById("fotonic-app-root");
  if (!root) return;

  var menuAnchor = document.querySelector("#adminmenu .current > a") ||
                   document.querySelector("#adminmenu .wp-has-current-submenu > a.wp-has-current-submenu");
  if (menuAnchor) {
    var navBg = window.getComputedStyle(menuAnchor).backgroundColor;
    if (navBg && navBg.indexOf("0, 0, 0, 0") === -1 && navBg !== "transparent") {
      root.style.setProperty("--fotonic-nav", navBg);
    }
  }

  var wrap = document.createElement("div");
  wrap.className = "wp-core-ui";
  wrap.style.cssText = "position:fixed;top:-999px;visibility:hidden;pointer-events:none;";
  wrap.innerHTML = "<button class=\"button-primary\"></button>";
  document.body.appendChild(wrap);
  var accentBg = window.getComputedStyle(wrap.querySelector(".button-primary")).backgroundColor;
  document.body.removeChild(wrap);
  if (accentBg && accentBg.indexOf("0, 0, 0, 0") === -1 && accentBg !== "transparent") {
    root.style.setProperty("--fotonic-primary", accentBg);
  }
})();', 'before' );

        // Load JS translations (generated by: wp i18n make-json languages/ --no-purge)
        wp_set_script_translations( 'fotonic-app-js', 'fotonic', FOTONIC_DIR . 'languages' );

        $pro_installed   = defined( 'FOTO_PRO_VERSION' );
        $license_valid   = false;

        if ( $pro_installed ) {
            $key = get_option( 'fotonic_pro_license_key', '' );
            if ( ! empty( $key ) ) {
                $cached        = get_transient( 'fotonic_pro_license_status' );
                $license_valid = is_array( $cached )
                    && ( $cached['result'] ?? '' ) === 'success'
                    && ( $cached['status'] ?? '' ) === 'active';
            }
        }

        wp_localize_script( 'fotonic-app-js', 'FotonicApp', [
            'restUrl'    => rest_url( 'fotonic/v1/' ),
            'nonce'      => wp_create_nonce( 'wp_rest' ),
            'isPro'      => $pro_installed,
            'version'    => FOTONIC_VERSION,
            'proVersion' => $pro_installed ? FOTO_PRO_VERSION : null,
            'locale'     => get_locale(),
            'dateFormat' => get_option( 'date_format', 'd/m/Y' ),
            'timeFormat' => get_option( 'time_format', 'H:i' ),
            'features' => [
                'kanban'        => $license_valid,
                'collaborators' => $license_valid,
                'analytics'     => $license_valid,
                'notifications' => $license_valid,
                'products'      => $license_valid,
                'suppliers'     => $license_valid,
                'calendar'      => true,
                'gcal'          => $license_valid && class_exists( 'Fotonic_Google_OAuth' ) && Fotonic_Google_OAuth::is_connected(),
                'expenses'      => $license_valid,
            ],
        ] );
    }
}
