/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  // Classes used by fotonic-pro, which ships no CSS of its own and is not scanned
  // by this config's `content` globs. Do not remove without checking Pro's source.
  safelist: [
    'bg-gray-50',
    'bg-green-50',
    'bg-indigo-50',
    'bg-red-50',
    'bg-red-600',
    'bg-white',
    'bg-yellow-50',
    'border',
    'border-gray-200',
    'border-gray-300',
    'border-indigo-300',
    'border-red-200',
    'border-solid',
    'border-yellow-200',
    'cursor-pointer',
    'disabled:cursor-not-allowed',
    'disabled:opacity-50',
    'divide-gray-100',
    'divide-gray-200',
    'divide-y',
    'flex',
    'flex-col',
    'flex-wrap',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-indigo-500',
    'font-medium',
    'font-mono',
    'font-semibold',
    'gap-1',
    'gap-1.5',
    'gap-2',
    'gap-4',
    'hover:bg-gray-50',
    'hover:bg-red-700',
    'hover:text-green-600',
    'hover:text-indigo-600',
    'inline-flex',
    'items-center',
    'justify-center',
    'min-w-full',
    'mt-0.5',
    'overflow-x-auto',
    'px-2',
    'px-3',
    'py-1.5',
    'py-2',
    'rounded',
    'rounded-lg',
    'rounded-md',
    'select-none',
    'space-y-3',
    'space-y-4',
    'text-gray-400',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-indigo-600',
    'text-indigo-700',
    'text-left',
    'text-red-600',
    'text-red-700',
    'text-sm',
    'text-white',
    'text-xs',
    'text-yellow-700',
    'transition-colors',
    'uppercase',
    'w-10',
    'w-32',
    'w-48',
    'w-full',
  ],
  corePlugins: { preflight: false },
  important: '#fotonic-app-root',
  theme: {
    extend: {
      colors: {
        'fotonic-primary': 'var(--fotonic-primary)',
      },
    },
  },
  plugins: [],
}
